// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/email": {
            "post": {
                "summary": "Enviar um Email",
                "description": "Envie um email com os detalhes fornecidos no corpo da solicitação.",
                "tags": ["Email"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [],
                "requestBody": {
                    "description": "Corpo da solicitação para enviar um e-mail",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "to": {
                                        "type": "string",
                                        "description": "O endereço de e-mail do destinatário."
                                    },
                                    "from": {
                                        "type": "string",
                                        "description": "O endereço de e-mail do remetente."
                                    },
                                    "subject": {
                                        "type": "string",
                                        "description": "O assunto do e-mail."
                                    },
                                    "body": {
                                        "type": "string"
                                    }
                                },
                                "required": ["to", "from", "subject"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Email enviado com sucesso.",
                        "schema": {
                            "type": "string",
                            "example": "email sent successfully!"
                        }
                    },
                    "400": {
                        "description": "Erro na solicitação.",
                        "schema": {
                            "type": "string",
                            "example": "Erro na solicitação."
                        }
                    }
                }
            }
        }
    }
}`



// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
